### ISSUE TITLE
support for current hackage ?

### ISSUE THREAD

**Issue by teto** [saep/nvim-hs-ghcid#1]
I would like to try this plugin on nixos but I can't because the bounds don't include the newer/current nvim-hs(-contrib) which are at version 2.
```
Using Parsec parser
Configuring nvim-hs-ghcid-1.0.0.0...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:950:20 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:460:12 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.4.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.4.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.4.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.4.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
nvim-hs >=1.0 && <2, nvim-hs-contrib >=1.0 && <2
```
Would it be possible to push an update on hackage please ?

**Comment by saep** [comment]
I've made a release (Version 2.0.0.0). It seems to work fine (tested it on this repository).

In any case, i've seen [this](https://github.com/aiya000/vim-ghcid-quickfix) on reddit a few weeks ago. It seems to have a nicer UI than this one, so it is probably preferable to use. 

I mainly wrote this to test the scripting API of nvim-hs and it's definitely nicer than vimL. However, since I'm barely ever managing to write any Haskell lately (and because I have switched to Emacs), I haven't really used this plugin at all. :-)
If you want to try something a bit more heavy-weight, I've found that the intero-(Emacs-)-plugin is really nice. I don't know about the (neo)vim one, though.
For the full IDE experience, HIE seems to be the way to go. However, every time I tried it, I couldn't get it to work, so I eventually gave up. I believe that has improved, though.

**Comment by teto** [comment]
cool ! Thanks for the update and the recommandation. I will try both (will wait for nixos to get the updated version in 2/3 days).
I already use HIE which lacks some LSP features but is already greater than anything else. I suggest to retry it as it has definitely improved alot and even I - a haskell noob - could make it work. I recommand coc.nvim + neovim master, it's really awesome (as in an IDE), here my hie setup in case you are interested https://github.com/teto/home/blob/master/config/nvim/coc-settings.json

**Comment by teto** [comment]
but there are some cases where HIE is not enough (to evaluate some expressions, to know their type for instance), which is why I wanna install ghcid
